In [2]:
from getpass import getpass
usuario = input('Tu usuario de GitHub: ')
token = getpass('Pegá tu token: ')
!git clone https://{usuario}:{token}@github.com/{usuario}/Cloud-Provider-Analytics-G2.git
%cd Cloud-Provider-Analytics-G2

Tu usuario de GitHub: camimattioli
Pegá tu token: ··········
Cloning into 'Cloud-Provider-Analytics-G2'...
remote: Enumerating objects: 33, done.
remote: Counting objects: 100% (33/33), done.
remote: Compressing objects: 100% (27/27), done.
remote: Total 33 (delta 6), reused 8 (delta 2), pack-reused 0 (from 0)
Receiving objects: 100% (33/33), 85.68 KiB | 1.82 MiB/s, done.
Resolving deltas: 100% (6/6), done.
/content/Cloud-Provider-Analytics-G2

In [3]:
!ls notebooks/
!ls datasets_clean/

limpieza_billing_monthly.ipynb
billing_monthly_limpio.csv

In [4]:
import pandas as pd

df = pd.read_csv('datasets_raw/billing_monthly.csv')
df.head()

,invoice_id,org_id,month,subtotal,credits,taxes,currency,exchange_rate_to_usd
0,inv_nym31sk0,org_xaji0y6d,2025-06-01,1133.34,NaN,238.00,USD,0.97684
1,inv_540sejok,org_xaji0y6d,2025-07-01,619.17,NaN,130.03,USD,1.00331
2,inv_ilp4vn2v,org_xaji0y6d,2025-08-01,540.79,NaN,113.57,ARS,0.00160
3,inv_27nls4sz,org_pbhsahxt,2025-06-01,520.91,NaN,109.39,ARS,0.00147
4,inv_xq1k1qrr,org_pbhsahxt,2025-07-01,909.56,NaN,191.01,EUR,1.09929

In [5]:
df.info()
df.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 240 entries, 0 to 239
Data columns (total 8 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   invoice_id            240 non-null    object
 1   org_id                240 non-null    object
 2   month                 240 non-null    object
 3   subtotal              240 non-null    float64
 4   credits               103 non-null    float64
 5   taxes                 240 non-null    float64
 6   currency              240 non-null    object
 7   exchange_rate_to_usd  240 non-null    float64
dtypes: float64(4), object(4)
memory usage: 15.1+ KB

invoice_id                0
org_id                    0
month                     0
subtotal                  0
credits                 137
taxes                     0
currency                  0
exchange_rate_to_usd      0
dtype: int64

In [6]:
df['credits'].describe()

count    103.000000
mean      19.099709
std       19.744169
min        0.000000
25%        4.490000
50%       12.600000
75%       24.465000
max       79.060000
Name: credits, dtype: float64

In [7]:
#Reemplazar nulos por cero
df['credits'] = df['credits'].fillna(0)
df['credits'].describe()

count    240.000000
mean       8.196958
std       16.003600
min        0.000000
25%        0.000000
50%        0.000000
75%       10.030000
max       79.060000
Name: credits, dtype: float64

Los valores nulos en credits no representan datos faltantes por error, sino facturas que no tuvieron ningún crédito aplicado. Por eso se completaron con 0 en vez de con la media, ya que la media distorsionaría el análisis asumiendo que todas las facturas tuvieron algún descuento.

In [8]:
#Convertir month a formato fecha, venía como texto
df['month'] = pd.to_datetime(df['month'])
df['month']

0     2025-06-01
1     2025-07-01
2     2025-08-01
3     2025-06-01
4     2025-07-01
         ...
235   2025-07-01
236   2025-08-01
237   2025-06-01
238   2025-07-01
239   2025-08-01
Name: month, Length: 240, dtype: datetime64[ns]

In [9]:
#Buscar duplicados
df.duplicated().sum()

np.int64(0)

In [10]:
#Revisar la columna currency para ver que esté todo escrito igual
df['currency'].value_counts()

#Se crean nuevas columnas con su valor en usd según cada exchange rate.
df['subtotal_usd'] = df['subtotal'] * df['exchange_rate_to_usd']
df['taxes_usd'] = df['taxes'] * df['exchange_rate_to_usd']
df['credits_usd'] = df['credits'] * df['exchange_rate_to_usd']

df.head()

,invoice_id,org_id,month,subtotal,credits,taxes,currency,exchange_rate_to_usd,subtotal_usd,taxes_usd,credits_usd
0,inv_nym31sk0,org_xaji0y6d,2025-06-01,1133.34,0.0,238.00,USD,0.97684,1107.091846,232.487920,0.0
1,inv_540sejok,org_xaji0y6d,2025-07-01,619.17,0.0,130.03,USD,1.00331,621.219453,130.460399,0.0
2,inv_ilp4vn2v,org_xaji0y6d,2025-08-01,540.79,0.0,113.57,ARS,0.00160,0.865264,0.181712,0.0
3,inv_27nls4sz,org_pbhsahxt,2025-06-01,520.91,0.0,109.39,ARS,0.00147,0.765738,0.160803,0.0
4,inv_xq1k1qrr,org_pbhsahxt,2025-07-01,909.56,0.0,191.01,EUR,1.09929,999.870212,209.975383,0.0

In [11]:
#Buscar outliers
df[['subtotal_usd', 'taxes_usd', 'credits_usd']].describe()

       subtotal_usd   taxes_usd  credits_usd
count    240.000000  240.000000   240.000000
mean     556.840282  134.115233     6.851754
std      587.814413  104.436413    15.319129
min    -1702.491362    0.079913     0.000000
25%        2.386977   56.113051     0.000000
50%      575.678411  130.270387     0.000000
75%      911.892592  194.230233     5.790402
max     2628.530520  551.989177    75.439888

In [12]:
df[df['subtotal_usd'] < 0]

,invoice_id,org_id,month,subtotal,credits,taxes,currency,exchange_rate_to_usd,subtotal_usd,taxes_usd,credits_usd
23,inv_gx8uwtk7,org_g0fn9xuy,2025-08-01,-1125.54,3.42,236.36,USD,1.00132,-1127.025713,236.671995,3.424514
74,inv_bmzw7539,org_i7p5tb94,2025-08-01,-849.43,18.20,178.38,USD,1.04212,-885.207992,185.893366,18.966584
89,inv_9rvn97y8,org_vyie6ivw,2025-08-01,-910.68,70.98,191.24,USD,0.96732,-880.918978,184.990277,68.660374
104,inv_3tlo1i7x,org_x7eedtjv,2025-08-01,-879.97,56.93,184.79,USD,0.95074,-836.622678,175.687245,54.125628
113,inv_4dqxin67,org_pac56t4u,2025-08-01,-701.47,2.71,147.31,USD,0.96736,-678.574019,142.501802,2.621546
149,inv_0kg6umh4,org_ktakpuxq,2025-08-01,-1355.74,0.00,284.71,ARS,0.00157,-2.128512,0.446995,0.000000
150,inv_gblckuhy,org_phr62gds,2025-06-01,-696.82,2.12,146.33,USD,0.99772,-695.231250,145.996368,2.115166
152,inv_93pomv7m,org_phr62gds,2025-08-01,-644.77,0.00,135.40,ARS,0.00135,-0.870440,0.182790,0.000000
162,inv_eskzadbs,org_g8sbi4q2,2025-06-01,-570.69,0.00,119.84,USD,0.85463,-487.728795,102.418859,0.000000
180,inv_mymmhlk1,org_nam148p0,2025-06-01,-538.22,1.21,113.03,USD,1.03612,-557.660506,117.112644,1.253705
181,inv_b17zyqzs,org_nam148p0,2025-07-01,-810.10,17.86,170.12,USD,1.07247,-868.807947,182.448596,19.154314
198,inv_jwe46xaa,org_afeyuhz1,2025-06-01,-1671.83,3.60,351.08,USD,1.01834,-1702.491362,357.518807,3.666024
206,inv_sy80w5gs,org_ly8ozcyw,2025-08-01,-1095.10,0.00,229.97,EUR,0.99810,-1093.019310,229.533057,0.000000

### Análisis de valores negativos en `subtotal`

Se detectaron 12 filas (5% del dataset) con `subtotal` negativo. Dado que la consigna
del dataset indica que incluye "créditos/ajustes", se interpreta que estas filas
representan ajustes o notas de crédito aplicadas a la facturación, y no errores de carga.
Por lo tanto, se conservan sin modificar, y se agrega una columna booleana para
identificarlas fácilmente en análisis posteriores.

In [13]:
#Se evalúa si hay outliers máximos
df[df['subtotal_usd'] == df['subtotal_usd'].max()]

,invoice_id,org_id,month,subtotal,credits,taxes,currency,exchange_rate_to_usd,subtotal_usd,taxes_usd,credits_usd
208,inv_633m236m,org_d14ve92m,2025-07-01,2237.39,21.64,469.85,EUR,1.17482,2628.53052,551.989177,25.423105

In [14]:
df.to_csv('datasets_clean/billing_monthly_limpio.csv', index=False)

In [ ]:
!git config --global user.email "camilamattioli97@gmail.com"
!git config --global user.name "Camila Mattioli"
!git add datasets_clean/billing_monthly_limpio.csv
!git add notebooks/limpieza_billing_monthly.ipynb
!git commit -m "Limpieza y transformación completa: nulos, fechas, monedas a USD, análisis de ajustes negativos"
!git push