In [18]:
import pandas as pd
#Se carga el archivo
df = pd.read_csv('data/raw/users.csv')
df.head(20)

,user_id,org_id,email,role,active,created_at,last_login
0,user_9tze5r5u,org_3t60rjiw,user_9tze5r5u@example.com,devops,True,2025-07-10,NaN
1,user_qpgb7r3o,org_afeyuhz1,user_qpgb7r3o@example.com,developer,True,2025-07-15,2025-08-10
2,user_cwbfuk9e,org_ykl1cq99,user_cwbfuk9e@example.com,developer,True,2025-06-12,2025-07-26
3,user_1v2isqp4,org_g8sbi4q2,user_1v2isqp4@example.com,developer,False,2025-05-12,NaN
4,user_9kwv08hh,org_pht0hl9x,user_9kwv08hh@example.com,ml_engineer,True,2025-08-01,2025-08-11
5,user_xfgcaqvk,org_pbhsahxt,user_xfgcaqvk@example.com,data_engineer,False,2025-07-26,2025-06-20
6,user_izzqy72w,org_41ibljh7,user_izzqy72w@example.com,data_engineer,True,2025-08-06,NaN
7,user_x7ptx63c,org_5iqvnb4g,user_x7ptx63c@example.com,ml_engineer,True,2025-06-20,2025-06-03
8,user_fl0ukeyz,org_jxepq85j,user_fl0ukeyz@example.com,analyst,True,2025-06-13,2025-06-06
9,user_7srcbplj,org_8mdd4v30,user_7srcbplj@example.com,devops,True,2025-07-12,2025-07-28
10,user_d84u89yj,org_253j2d54,user_d84u89yj@example.com,ml_engineer,True,2025-06-28,2025-07-24
11,user_b1qx6gvw,org_n9j2qp89,user_b1qx6gvw@example.com,developer,True,2025-07-02,2025-07-19
12,user_rdmly4ly,org_pnsm43d8,user_rdmly4ly@example.com,ml_engineer,True,2025-06-13,2025-08-06
13,user_k83tqll8,org_pbhsahxt,user_k83tqll8@example.com,devops,True,2025-05-12,2025-07-19
14,user_os9xtogn,org_cwi64ciy,user_os9xtogn@example.com,analyst,True,2025-08-03,2025-08-01
15,user_1w1ht7pz,org_rixa11dp,user_1w1ht7pz@example.com,data_engineer,True,2025-08-05,2025-08-02
16,user_e9vifttd,org_zhwjr64d,user_e9vifttd@example.com,data_engineer,True,2025-07-27,2025-08-15
17,user_96qe3rzs,org_trp0j43d,user_96qe3rzs@example.com,analyst,True,2025-05-11,2025-08-02
18,user_j49itn7s,org_i3qk2iag,user_j49itn7s@example.com,ml_engineer,True,2025-05-11,NaN
19,user_55j2o7s3,org_phr62gds,user_55j2o7s3@example.com,devops,True,2025-06-09,2025-05-24

In [12]:
#Verifico el tipo de datos
print(df.dtypes)

user_id               object
org_id                object
email                 object
role                  object
active                  bool
created_at    datetime64[ns]
last_login    datetime64[ns]
dtype: object

In [14]:
#Transformo las columnas de fecha a datatime
date_cols = ['created_at', 'last_login']
for col in date_cols:
    df[col] = pd.to_datetime(df[col], errors='coerce')

In [28]:
#Verifico duplicado
total_duplicados = df.duplicated().sum()
print(f"Filas duplicadas totales: {total_duplicados}")

#Mostrar las filas duplicadas para inspeccionarlas (keep=False muestra todas las apariciones)
filas_duplicadas = df[df.duplicated(keep=False)]
print(filas_duplicadas)

Filas duplicadas totales: 0
Empty DataFrame
Columns: [user_id, org_id, email, role, active, created_at, last_login]
Index: []

In [21]:
#Verifico si existen duplicados de usuarios o de mail
user_duplicados = df['user_id'].duplicated().sum()
email_duplicados = df['email'].duplicated().sum()

print(f"IDs duplicados: {user_duplicados}")
print(f"Emails duplicados: {email_duplicados}")

#Filas que comparten un mismo correo
df[df['email'].duplicated(keep=False)]

IDs duplicados: 0
Emails duplicados: 0

Empty DataFrame
Columns: [user_id, org_id, email, role, active, created_at, last_login]
Index: []

In [17]:
#Se verifican y corrigen incoherencias como ejemplo la fila N°5 donde el ultimo ingreso es antes que la creación de la cuenta

mask_invalid_date = df['last_login'] < df['created_at']
df.loc[mask_invalid_date, 'last_login'] = pd.NaT

In [24]:
#Normalización de texto
df['email'] = df['email'].astype(str).str.strip().str.lower()
df['role'] = df['role'].astype(str).str.strip()

In [26]:
#Guardo la versión limpia

df.to_csv('data/clean/users_limpio.csv', index=False)
print("--- Limpieza completada con éxito ---")
print(f"Total registros: {len(df)}")
print(f"Fechas incoherentes corregidas a nulo: {mask_invalid_date.sum()}")
print(f"Registros sin último inicio de sesión (NaT): {df['last_login'].isna().sum()}")

--- Limpieza completada con éxito ---
Total registros: 800
Fechas incoherentes corregidas a nulo: 0
Registros sin último inicio de sesión (NaT): 139

In [27]:
display(df)

,user_id,org_id,email,role,active,created_at,last_login
0,user_9tze5r5u,org_3t60rjiw,user_9tze5r5u@example.com,devops,True,2025-07-10,NaN
1,user_qpgb7r3o,org_afeyuhz1,user_qpgb7r3o@example.com,developer,True,2025-07-15,2025-08-10
2,user_cwbfuk9e,org_ykl1cq99,user_cwbfuk9e@example.com,developer,True,2025-06-12,2025-07-26
3,user_1v2isqp4,org_g8sbi4q2,user_1v2isqp4@example.com,developer,False,2025-05-12,NaN
4,user_9kwv08hh,org_pht0hl9x,user_9kwv08hh@example.com,ml_engineer,True,2025-08-01,2025-08-11
...,...,...,...,...,...,...,...
795,user_lu3ndz3c,org_pbhsahxt,user_lu3ndz3c@example.com,admin,True,2025-06-05,2025-07-29
796,user_c5rqnsvs,org_g8sbi4q2,user_c5rqnsvs@example.com,developer,True,2025-08-10,2025-08-22
797,user_ojrpp7r9,org_9t84azyt,user_ojrpp7r9@example.com,devops,True,2025-07-03,2025-08-22
798,user_3fezez5e,org_id25owf7,user_3fezez5e@example.com,data_engineer,True,2025-05-04,2025-06-11
799,user_hr07n8vo,org_pnsm43d8,user_hr07n8vo@example.com,devops,True,2025-07-14,NaN

In [31]:
#descargo el archivo
from google.colab import files

files.download('data/clean/users_limpio.csv')